import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { getLiveData } from "@/utils/pageData";
import { GLOBAL } from "@/queries/global";
import { GlobalProps } from "@/utils/types";
import { Header } from "@/components/Header";

const montSans = Montserrat({
  variable: "--font-geist-sans",
  weight: ["400", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {
    data,
  }: {
    data: GlobalProps;
  } = await getLiveData({
    query: GLOBAL,
    params: {
      slug: "/",
    },
    usePreview: false,
  });

  const navigation = data?.locations.map((location) => ({
    _key: location._id,
    text: location.name,
    href: location.slug,
  }));

  return (
    <html lang="en">
      <body className={`${montSans.variable} antialiased leading-[1.3]`}>
        <Header items={navigation} tagline={data.siteTagline} />

        <main>{children}</main>
      </body>
    </html>
  );
}
