import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { getLiveData } from "@/utils/pageData";
import { GLOBAL } from "@/queries/global";
import { GlobalProps } from "@/utils/types";

const montSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    data,
  }: {
    data: GlobalProps;
  } = await getLiveData({
    query: GLOBAL,
    params: {
      slug: "/",
    },
    usePreview: false,
  });

  return (
    <html lang="en">
      <body className={`${montSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
